# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Projects/fpga/calculator/calculator.cache/wt [current_project]
set_property parent.project_path D:/Projects/fpga/calculator/calculator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  D:/Projects/fpga/calculator/calculator.srcs/sources_1/imports/src/adder.vhd
  D:/Projects/fpga/calculator/calculator.srcs/sources_1/imports/src/freqdiv.vhd
  D:/Projects/fpga/calculator/calculator.srcs/sources_1/imports/src/register.vhd
  D:/Projects/fpga/calculator/calculator.srcs/sources_1/imports/src/counter.vhd
  D:/Projects/fpga/calculator/calculator.srcs/sources_1/imports/src/tff.vhd
  D:/Projects/fpga/calculator/calculator.srcs/sources_1/imports/src/bcdtobinary.vhd
  D:/Projects/fpga/calculator/calculator.srcs/sources_1/imports/src/display.vhd
  D:/Projects/fpga/calculator/calculator.srcs/sources_1/imports/src/debouncer.vhd
  D:/Projects/fpga/calculator/calculator.srcs/sources_1/imports/src/decoderbcd.vhd
  D:/Projects/fpga/calculator/calculator.srcs/sources_1/imports/src/reader.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Projects/fpga/calculator/calculator.srcs/constrs_1/new/constrs.xdc
set_property used_in_implementation false [get_files D:/Projects/fpga/calculator/calculator.srcs/constrs_1/new/constrs.xdc]


synth_design -top READER -part xc7a35tcpg236-1


write_checkpoint -force -noxdef READER.dcp

catch { report_utilization -file READER_utilization_synth.rpt -pb READER_utilization_synth.pb }
