set_property PACKAGE_PIN W5 [get_ports C]							
	set_property IOSTANDARD LVCMOS33 [get_ports C]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports C]

set_property PACKAGE_PIN W7 [get_ports SEGM[0]]					
        set_property IOSTANDARD LVCMOS33 [get_ports SEGM[0]]
    set_property PACKAGE_PIN W6 [get_ports SEGM[1]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports SEGM[1]]
    set_property PACKAGE_PIN U8 [get_ports SEGM[2]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports SEGM[2]]
    set_property PACKAGE_PIN V8 [get_ports SEGM[3]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports SEGM[3]]
    set_property PACKAGE_PIN U5 [get_ports SEGM[4]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports SEGM[4]]
    set_property PACKAGE_PIN V5 [get_ports SEGM[5]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports SEGM[5]]
    set_property PACKAGE_PIN U7 [get_ports SEGM[6]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports SEGM[6]]
        
set_property PACKAGE_PIN U18 [get_ports CONFIRM]						
            set_property IOSTANDARD LVCMOS33 [get_ports CONFIRM]
            
set_property PACKAGE_PIN U1 [get_ports ENU]					
                set_property IOSTANDARD LVCMOS33 [get_ports ENU]
            set_property PACKAGE_PIN T1 [get_ports ENZ]                    
                set_property IOSTANDARD LVCMOS33 [get_ports ENZ]
            set_property PACKAGE_PIN R2 [get_ports ENH]                    
                set_property IOSTANDARD LVCMOS33 [get_ports ENH]
                
set_property PACKAGE_PIN V3 [get_ports NUMBER[6]]					
                    set_property IOSTANDARD LVCMOS33 [get_ports NUMBER[6]]
                set_property PACKAGE_PIN W3 [get_ports NUMBER[5]]                    
                    set_property IOSTANDARD LVCMOS33 [get_ports NUMBER[5]]
                set_property PACKAGE_PIN U3 [get_ports NUMBER[4]]                    
                    set_property IOSTANDARD LVCMOS33 [get_ports NUMBER[4]]
                set_property PACKAGE_PIN P3 [get_ports NUMBER[3]]                    
                    set_property IOSTANDARD LVCMOS33 [get_ports NUMBER[3]]
                set_property PACKAGE_PIN N3 [get_ports NUMBER[2]]                    
                    set_property IOSTANDARD LVCMOS33 [get_ports NUMBER[2]]
                set_property PACKAGE_PIN P1 [get_ports NUMBER[1]]                    
                    set_property IOSTANDARD LVCMOS33 [get_ports NUMBER[1]]
                set_property PACKAGE_PIN L1 [get_ports NUMBER[0]]                    
                    set_property IOSTANDARD LVCMOS33 [get_ports NUMBER[0]]
                    
set_property PACKAGE_PIN U2 [get_ports AN[0]]					
                        set_property IOSTANDARD LVCMOS33 [get_ports AN[0]]
                    set_property PACKAGE_PIN U4 [get_ports AN[1]]                    
                        set_property IOSTANDARD LVCMOS33 [get_ports AN[1]]
                    set_property PACKAGE_PIN V4 [get_ports AN[2]]                    
                        set_property IOSTANDARD LVCMOS33 [get_ports AN[2]]
                    set_property PACKAGE_PIN W4 [get_ports AN[3]]                    
                        set_property IOSTANDARD LVCMOS33 [get_ports AN[3]]